// Generated from: features\queue.feature
import { test } from "playwright-bdd";

test.describe('Queue functionality', () => {

  test.beforeEach('Background', async ({ Given, And, page }, testInfo) => { if (testInfo.error) return;
    await Given('user launches the application', null, { page }); 
    await And('user clicks on sign in link', null, { page }); 
    await And('user enters "valid" credentials', null, { page }); 
    await And('user clicks login button', null, { page }); 
  });
  
  test('Navigate to Queue page', async ({ When, Then, page }) => { 
    await When('user clicks on Queue Get Started button', null, { page }); 
    await Then('user should be redirected to Queue page', null, { page }); 
  });

  test('Navigate to Implementation of Queue in Python page', async ({ Given, When, Then, page }) => { 
    await Given('user is on Queue page', null, { page }); 
    await When('user clicks on "Implementation of Queue in Python"', null, { page }); 
    await Then('user should be navigated to Implementation of Queue in Python page', null, { page }); 
  });

  test('Navigate to Try Editor-Python', async ({ Given, When, Then, page }) => { 
    await Given('user is on Implementation of Queue in Python page', null, { page }); 
    await When('user clicks Try Here button', null, { page }); 
    await Then('user should be navigated to try editor page', null, { page }); 
  });

  test('Run valid python code-Python', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page for Queue Implementation', null, { page }); 
    await When('user runs python code of type "valid"', null, { page }); 
    await Then('user should see output for "valid"', null, { page }); 
  });

  test('Run invalid python code-Python', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page for Queue Implementation', null, { page }); 
    await When('user runs python code of type "invalid"', null, { page }); 
    await Then('user should see output for "invalid"', null, { page }); 
  });

  test('Run empty python code-Python', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page for Queue Implementation', null, { page }); 
    await When('user runs python code of type "empty"', null, { page }); 
    await Then('user should see output for "empty"', null, { page }); 
  });

  test('Navigate back to Queue page from editor-Python', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page', null, { page }); 
    await When('user clicks browser back button', null, { page }); 
    await Then('user should be navigated back to Queue page', null, { page }); 
  });

  test('Navigate to Implementation using collections.deque page', async ({ Given, When, Then, page }) => { 
    await Given('user is on Queue page', null, { page }); 
    await When('user clicks "Implementation using collections.deque"', null, { page }); 
    await Then('user should be redirected to Implementation using collections.deque page.', null, { page }); 
  });

  test('Navigate to Try Editor-Deque', async ({ Given, When, Then, page }) => { 
    await Given('user is on Implementation using collections.deque page', null, { page }); 
    await When('user clicks Try Here button', null, { page }); 
    await Then('user should be navigated to try editor page', null, { page }); 
  });

  test('Run valid python code-Deque', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page for Queue Implementation using collections.deque', null, { page }); 
    await When('user runs python code of type "valid"', null, { page }); 
    await Then('user should see output for "valid"', null, { page }); 
  });

  test('Run invalid python code-Deque', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page for Queue Implementation using collections.deque', null, { page }); 
    await When('user runs python code of type "invalid"', null, { page }); 
    await Then('user should see output for "invalid"', null, { page }); 
  });

  test('Run empty python code-Deque', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page for Queue Implementation using collections.deque', null, { page }); 
    await When('user runs python code of type "empty"', null, { page }); 
    await Then('user should see output for "empty"', null, { page }); 
  });

  test('Navigate back to Queue page from editor-Deque', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page', null, { page }); 
    await When('user clicks browser back button', null, { page }); 
    await Then('user should be navigated back to Queue page', null, { page }); 
  });

  test('Navigate to Implementation using array page', async ({ Given, When, Then, page }) => { 
    await Given('user is on Queue page', null, { page }); 
    await When('user clicks on "Implementation using array"', null, { page }); 
    await Then('user should be navigated to Implementation using array page', null, { page }); 
  });

  test('Navigate to Try Editor-Array', async ({ Given, When, Then, page }) => { 
    await Given('user is on Implementation using array page', null, { page }); 
    await When('user clicks Try Here button', null, { page }); 
    await Then('user should be navigated to try editor page', null, { page }); 
  });

  test('Run valid python code-Array', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page for Queue Implementation using array', null, { page }); 
    await When('user runs python code of type "valid"', null, { page }); 
    await Then('user should see output for "valid"', null, { page }); 
  });

  test('Run invalid python code-Array', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page for Queue Implementation using array', null, { page }); 
    await When('user runs python code of type "invalid"', null, { page }); 
    await Then('user should see output for "invalid"', null, { page }); 
  });

  test('Run empty python code-Array', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page for Queue Implementation using array', null, { page }); 
    await When('user runs python code of type "empty"', null, { page }); 
    await Then('user should see output for "empty"', null, { page }); 
  });

  test('Navigate back to Queue page from editor-Array', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page', null, { page }); 
    await When('user clicks browser back button', null, { page }); 
    await Then('user should be navigated back to Queue page', null, { page }); 
  });

  test('Navigate to Queue Operations page', async ({ Given, When, Then, page }) => { 
    await Given('user is on Queue page', null, { page }); 
    await When('user clicks "Queue Operations"', null, { page }); 
    await Then('user should be redirected to Queue Operations page.', null, { page }); 
  });

  test('Navigate to Try Editor-Queue Operations', async ({ Given, When, Then, page }) => { 
    await Given('user is on Queue Operations page', null, { page }); 
    await When('user clicks Try Here button', null, { page }); 
    await Then('user should be navigated to try editor page', null, { page }); 
  });

  test('Run valid python code-Queue Operations', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page for Queue Queue Operations', null, { page }); 
    await When('user runs python code of type "valid"', null, { page }); 
    await Then('user should see output for "valid"', null, { page }); 
  });

  test('Run invalid python code-Queue Operations', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page for Queue Queue Operations', null, { page }); 
    await When('user runs python code of type "invalid"', null, { page }); 
    await Then('user should see output for "invalid"', null, { page }); 
  });

  test('Run empty python code-Queue Operations', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page for Queue Queue Operations', null, { page }); 
    await When('user runs python code of type "empty"', null, { page }); 
    await Then('user should see output for "empty"', null, { page }); 
  });

  test('Navigate back to Queue page from editor-Queue Operations', async ({ Given, When, Then, page }) => { 
    await Given('user is on try editor page', null, { page }); 
    await When('user clicks browser back button', null, { page }); 
    await Then('user should be navigated back to Queue page', null, { page }); 
  });

  test('Navigate to Practice Questions page', async ({ Given, When, Then, page }) => { 
    await Given('user is on Queue page', null, { page }); 
    await When('user clicks "Practice Questions"', null, { page }); 
    await Then('user should be redirected to practice questions page', null, { page }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features\\queue.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":13,"pickleLine":9,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When user clicks on Queue Get Started button","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then user should be redirected to Queue page","stepMatchArguments":[]}]},
  {"pwTestLine":18,"pickleLine":13,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":19,"gherkinStepLine":14,"keywordType":"Context","textWithKeyword":"Given user is on Queue page","stepMatchArguments":[]},{"pwStepLine":20,"gherkinStepLine":15,"keywordType":"Action","textWithKeyword":"When user clicks on \"Implementation of Queue in Python\"","stepMatchArguments":[{"group":{"start":15,"value":"\"Implementation of Queue in Python\"","children":[{"start":16,"value":"Implementation of Queue in Python","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"Then user should be navigated to Implementation of Queue in Python page","stepMatchArguments":[]}]},
  {"pwTestLine":24,"pickleLine":18,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":25,"gherkinStepLine":19,"keywordType":"Context","textWithKeyword":"Given user is on Implementation of Queue in Python page","stepMatchArguments":[]},{"pwStepLine":26,"gherkinStepLine":20,"keywordType":"Action","textWithKeyword":"When user clicks Try Here button","stepMatchArguments":[]},{"pwStepLine":27,"gherkinStepLine":21,"keywordType":"Outcome","textWithKeyword":"Then user should be navigated to try editor page","stepMatchArguments":[]}]},
  {"pwTestLine":30,"pickleLine":24,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":31,"gherkinStepLine":25,"keywordType":"Context","textWithKeyword":"Given user is on try editor page for Queue Implementation","stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":26,"keywordType":"Action","textWithKeyword":"When user runs python code of type \"valid\"","stepMatchArguments":[{"group":{"start":30,"value":"\"valid\"","children":[{"start":31,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":27,"keywordType":"Outcome","textWithKeyword":"Then user should see output for \"valid\"","stepMatchArguments":[{"group":{"start":27,"value":"\"valid\"","children":[{"start":28,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":36,"pickleLine":29,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":37,"gherkinStepLine":30,"keywordType":"Context","textWithKeyword":"Given user is on try editor page for Queue Implementation","stepMatchArguments":[]},{"pwStepLine":38,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"When user runs python code of type \"invalid\"","stepMatchArguments":[{"group":{"start":30,"value":"\"invalid\"","children":[{"start":31,"value":"invalid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then user should see output for \"invalid\"","stepMatchArguments":[{"group":{"start":27,"value":"\"invalid\"","children":[{"start":28,"value":"invalid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":42,"pickleLine":34,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":43,"gherkinStepLine":35,"keywordType":"Context","textWithKeyword":"Given user is on try editor page for Queue Implementation","stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":36,"keywordType":"Action","textWithKeyword":"When user runs python code of type \"empty\"","stepMatchArguments":[{"group":{"start":30,"value":"\"empty\"","children":[{"start":31,"value":"empty","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":37,"keywordType":"Outcome","textWithKeyword":"Then user should see output for \"empty\"","stepMatchArguments":[{"group":{"start":27,"value":"\"empty\"","children":[{"start":28,"value":"empty","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":48,"pickleLine":39,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":49,"gherkinStepLine":40,"keywordType":"Context","textWithKeyword":"Given user is on try editor page","stepMatchArguments":[]},{"pwStepLine":50,"gherkinStepLine":41,"keywordType":"Action","textWithKeyword":"When user clicks browser back button","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":42,"keywordType":"Outcome","textWithKeyword":"Then user should be navigated back to Queue page","stepMatchArguments":[]}]},
  {"pwTestLine":54,"pickleLine":44,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":55,"gherkinStepLine":45,"keywordType":"Context","textWithKeyword":"Given user is on Queue page","stepMatchArguments":[]},{"pwStepLine":56,"gherkinStepLine":46,"keywordType":"Action","textWithKeyword":"When user clicks \"Implementation using collections.deque\"","stepMatchArguments":[{"group":{"start":12,"value":"\"Implementation using collections.deque\"","children":[{"start":13,"value":"Implementation using collections.deque","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":57,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"Then user should be redirected to Implementation using collections.deque page.","stepMatchArguments":[]}]},
  {"pwTestLine":60,"pickleLine":48,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":61,"gherkinStepLine":49,"keywordType":"Context","textWithKeyword":"Given user is on Implementation using collections.deque page","stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When user clicks Try Here button","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then user should be navigated to try editor page","stepMatchArguments":[]}]},
  {"pwTestLine":66,"pickleLine":54,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":67,"gherkinStepLine":55,"keywordType":"Context","textWithKeyword":"Given user is on try editor page for Queue Implementation using collections.deque","stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":56,"keywordType":"Action","textWithKeyword":"When user runs python code of type \"valid\"","stepMatchArguments":[{"group":{"start":30,"value":"\"valid\"","children":[{"start":31,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":69,"gherkinStepLine":57,"keywordType":"Outcome","textWithKeyword":"Then user should see output for \"valid\"","stepMatchArguments":[{"group":{"start":27,"value":"\"valid\"","children":[{"start":28,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":72,"pickleLine":59,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":73,"gherkinStepLine":60,"keywordType":"Context","textWithKeyword":"Given user is on try editor page for Queue Implementation using collections.deque","stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":61,"keywordType":"Action","textWithKeyword":"When user runs python code of type \"invalid\"","stepMatchArguments":[{"group":{"start":30,"value":"\"invalid\"","children":[{"start":31,"value":"invalid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":62,"keywordType":"Outcome","textWithKeyword":"Then user should see output for \"invalid\"","stepMatchArguments":[{"group":{"start":27,"value":"\"invalid\"","children":[{"start":28,"value":"invalid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":78,"pickleLine":64,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":79,"gherkinStepLine":65,"keywordType":"Context","textWithKeyword":"Given user is on try editor page for Queue Implementation using collections.deque","stepMatchArguments":[]},{"pwStepLine":80,"gherkinStepLine":66,"keywordType":"Action","textWithKeyword":"When user runs python code of type \"empty\"","stepMatchArguments":[{"group":{"start":30,"value":"\"empty\"","children":[{"start":31,"value":"empty","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":81,"gherkinStepLine":67,"keywordType":"Outcome","textWithKeyword":"Then user should see output for \"empty\"","stepMatchArguments":[{"group":{"start":27,"value":"\"empty\"","children":[{"start":28,"value":"empty","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":84,"pickleLine":68,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":85,"gherkinStepLine":69,"keywordType":"Context","textWithKeyword":"Given user is on try editor page","stepMatchArguments":[]},{"pwStepLine":86,"gherkinStepLine":70,"keywordType":"Action","textWithKeyword":"When user clicks browser back button","stepMatchArguments":[]},{"pwStepLine":87,"gherkinStepLine":71,"keywordType":"Outcome","textWithKeyword":"Then user should be navigated back to Queue page","stepMatchArguments":[]}]},
  {"pwTestLine":90,"pickleLine":72,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":91,"gherkinStepLine":73,"keywordType":"Context","textWithKeyword":"Given user is on Queue page","stepMatchArguments":[]},{"pwStepLine":92,"gherkinStepLine":74,"keywordType":"Action","textWithKeyword":"When user clicks on \"Implementation using array\"","stepMatchArguments":[{"group":{"start":15,"value":"\"Implementation using array\"","children":[{"start":16,"value":"Implementation using array","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":93,"gherkinStepLine":75,"keywordType":"Outcome","textWithKeyword":"Then user should be navigated to Implementation using array page","stepMatchArguments":[]}]},
  {"pwTestLine":96,"pickleLine":76,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":97,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"Given user is on Implementation using array page","stepMatchArguments":[]},{"pwStepLine":98,"gherkinStepLine":78,"keywordType":"Action","textWithKeyword":"When user clicks Try Here button","stepMatchArguments":[]},{"pwStepLine":99,"gherkinStepLine":79,"keywordType":"Outcome","textWithKeyword":"Then user should be navigated to try editor page","stepMatchArguments":[]}]},
  {"pwTestLine":102,"pickleLine":82,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":103,"gherkinStepLine":83,"keywordType":"Context","textWithKeyword":"Given user is on try editor page for Queue Implementation using array","stepMatchArguments":[]},{"pwStepLine":104,"gherkinStepLine":84,"keywordType":"Action","textWithKeyword":"When user runs python code of type \"valid\"","stepMatchArguments":[{"group":{"start":30,"value":"\"valid\"","children":[{"start":31,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":105,"gherkinStepLine":85,"keywordType":"Outcome","textWithKeyword":"Then user should see output for \"valid\"","stepMatchArguments":[{"group":{"start":27,"value":"\"valid\"","children":[{"start":28,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":108,"pickleLine":87,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":109,"gherkinStepLine":88,"keywordType":"Context","textWithKeyword":"Given user is on try editor page for Queue Implementation using array","stepMatchArguments":[]},{"pwStepLine":110,"gherkinStepLine":89,"keywordType":"Action","textWithKeyword":"When user runs python code of type \"invalid\"","stepMatchArguments":[{"group":{"start":30,"value":"\"invalid\"","children":[{"start":31,"value":"invalid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":111,"gherkinStepLine":90,"keywordType":"Outcome","textWithKeyword":"Then user should see output for \"invalid\"","stepMatchArguments":[{"group":{"start":27,"value":"\"invalid\"","children":[{"start":28,"value":"invalid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":114,"pickleLine":92,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":115,"gherkinStepLine":93,"keywordType":"Context","textWithKeyword":"Given user is on try editor page for Queue Implementation using array","stepMatchArguments":[]},{"pwStepLine":116,"gherkinStepLine":94,"keywordType":"Action","textWithKeyword":"When user runs python code of type \"empty\"","stepMatchArguments":[{"group":{"start":30,"value":"\"empty\"","children":[{"start":31,"value":"empty","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":117,"gherkinStepLine":95,"keywordType":"Outcome","textWithKeyword":"Then user should see output for \"empty\"","stepMatchArguments":[{"group":{"start":27,"value":"\"empty\"","children":[{"start":28,"value":"empty","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":120,"pickleLine":97,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":121,"gherkinStepLine":98,"keywordType":"Context","textWithKeyword":"Given user is on try editor page","stepMatchArguments":[]},{"pwStepLine":122,"gherkinStepLine":99,"keywordType":"Action","textWithKeyword":"When user clicks browser back button","stepMatchArguments":[]},{"pwStepLine":123,"gherkinStepLine":100,"keywordType":"Outcome","textWithKeyword":"Then user should be navigated back to Queue page","stepMatchArguments":[]}]},
  {"pwTestLine":126,"pickleLine":101,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":127,"gherkinStepLine":102,"keywordType":"Context","textWithKeyword":"Given user is on Queue page","stepMatchArguments":[]},{"pwStepLine":128,"gherkinStepLine":103,"keywordType":"Action","textWithKeyword":"When user clicks \"Queue Operations\"","stepMatchArguments":[{"group":{"start":12,"value":"\"Queue Operations\"","children":[{"start":13,"value":"Queue Operations","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":129,"gherkinStepLine":104,"keywordType":"Outcome","textWithKeyword":"Then user should be redirected to Queue Operations page.","stepMatchArguments":[]}]},
  {"pwTestLine":132,"pickleLine":105,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":133,"gherkinStepLine":106,"keywordType":"Context","textWithKeyword":"Given user is on Queue Operations page","stepMatchArguments":[]},{"pwStepLine":134,"gherkinStepLine":107,"keywordType":"Action","textWithKeyword":"When user clicks Try Here button","stepMatchArguments":[]},{"pwStepLine":135,"gherkinStepLine":108,"keywordType":"Outcome","textWithKeyword":"Then user should be navigated to try editor page","stepMatchArguments":[]}]},
  {"pwTestLine":138,"pickleLine":111,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":139,"gherkinStepLine":112,"keywordType":"Context","textWithKeyword":"Given user is on try editor page for Queue Queue Operations","stepMatchArguments":[]},{"pwStepLine":140,"gherkinStepLine":113,"keywordType":"Action","textWithKeyword":"When user runs python code of type \"valid\"","stepMatchArguments":[{"group":{"start":30,"value":"\"valid\"","children":[{"start":31,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":141,"gherkinStepLine":114,"keywordType":"Outcome","textWithKeyword":"Then user should see output for \"valid\"","stepMatchArguments":[{"group":{"start":27,"value":"\"valid\"","children":[{"start":28,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":144,"pickleLine":116,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":145,"gherkinStepLine":117,"keywordType":"Context","textWithKeyword":"Given user is on try editor page for Queue Queue Operations","stepMatchArguments":[]},{"pwStepLine":146,"gherkinStepLine":118,"keywordType":"Action","textWithKeyword":"When user runs python code of type \"invalid\"","stepMatchArguments":[{"group":{"start":30,"value":"\"invalid\"","children":[{"start":31,"value":"invalid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":147,"gherkinStepLine":119,"keywordType":"Outcome","textWithKeyword":"Then user should see output for \"invalid\"","stepMatchArguments":[{"group":{"start":27,"value":"\"invalid\"","children":[{"start":28,"value":"invalid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":150,"pickleLine":121,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":151,"gherkinStepLine":122,"keywordType":"Context","textWithKeyword":"Given user is on try editor page for Queue Queue Operations","stepMatchArguments":[]},{"pwStepLine":152,"gherkinStepLine":123,"keywordType":"Action","textWithKeyword":"When user runs python code of type \"empty\"","stepMatchArguments":[{"group":{"start":30,"value":"\"empty\"","children":[{"start":31,"value":"empty","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":153,"gherkinStepLine":124,"keywordType":"Outcome","textWithKeyword":"Then user should see output for \"empty\"","stepMatchArguments":[{"group":{"start":27,"value":"\"empty\"","children":[{"start":28,"value":"empty","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":156,"pickleLine":126,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":157,"gherkinStepLine":127,"keywordType":"Context","textWithKeyword":"Given user is on try editor page","stepMatchArguments":[]},{"pwStepLine":158,"gherkinStepLine":128,"keywordType":"Action","textWithKeyword":"When user clicks browser back button","stepMatchArguments":[]},{"pwStepLine":159,"gherkinStepLine":129,"keywordType":"Outcome","textWithKeyword":"Then user should be navigated back to Queue page","stepMatchArguments":[]}]},
  {"pwTestLine":162,"pickleLine":130,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user launches the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And user clicks on sign in link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And user enters \"valid\" credentials","isBg":true,"stepMatchArguments":[{"group":{"start":12,"value":"\"valid\"","children":[{"start":13,"value":"valid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And user clicks login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":163,"gherkinStepLine":131,"keywordType":"Context","textWithKeyword":"Given user is on Queue page","stepMatchArguments":[]},{"pwStepLine":164,"gherkinStepLine":132,"keywordType":"Action","textWithKeyword":"When user clicks \"Practice Questions\"","stepMatchArguments":[{"group":{"start":12,"value":"\"Practice Questions\"","children":[{"start":13,"value":"Practice Questions","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":165,"gherkinStepLine":133,"keywordType":"Outcome","textWithKeyword":"Then user should be redirected to practice questions page","stepMatchArguments":[]}]},
]; // bdd-data-end